---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-akuity-io-v1-networking
  failurePolicy: Fail
  name: vnetworking-v1.kb.io
  rules:
  - apiGroups:
    - akuity.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkings
  sideEffects: None
