apiVersion: akuity.io/v1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: namespace-class-operator
    app.kubernetes.io/managed-by: kustomize
  name: namespaceclass-sample
spec:
  networking:
    networkpolicies:
    - name: test-network-policy
      spec:
        podSelector:
          matchLabels:
            role: db
        policyTypes:
        - Ingress
        - Egress
