apiVersion: akuity.io/v1
kind: Networking
metadata:
  labels:
    app.kubernetes.io/name: namespace-class-operator
    app.kubernetes.io/managed-by: kustomize
  name: networking-sample
spec:
  # TODO(user): Add fields here
