apiVersion: akuity.io/v1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: namespace-class-operator
    app.kubernetes.io/managed-by: kustomize
  name: namespaceclass-sample
spec:
  # TODO(user): Add fields here
