apiVersion: akuity.io/v1
kind: Networking
metadata:
  labels:
    app.kubernetes.io/name: namespace-class-operator
    app.kubernetes.io/managed-by: kustomize
  name: networking-sample
spec:
  networkpolicies:
  - name: test-network-policy1
    spec:
      podSelector:
        matchLabels:
          role: db
      policyTypes:
      - Ingress
      - Egress
  - name: test-network-policy2
    spec:
      podSelector:
        matchLabels:
          role: db
      policyTypes:
      - Ingress
      - Egress
