apiVersion: akuity.io/v1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: namespace-class-operator
    app.kubernetes.io/managed-by: kustomize
  name: internal-network
spec:
  networking:
    networkpolicies:
    - name: database
      spec:
        podSelector:
          matchLabels:
            role: database
        policyTypes:
        - Ingress
        - Egress
---
apiVersion: akuity.io/v1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: namespace-class-operator
    app.kubernetes.io/managed-by: kustomize
  name: public-network
spec:
  networking:
    networkpolicies:
    - name: frontend
      spec:
        podSelector:
          matchLabels:
            role: frontend
        policyTypes:
        - Ingress
        - Egress